#info
spring.application.name=Salus.API
api.info.version=1.3

#SQL Database Settings
spring.datasource.url=${SQL_CONN:jdbc:sqlserver://localhost;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;applicationName=Api}
spring.datasource.username=${SQL_USER:sa}
spring.datasource.password=${SQL_PWD:Ba705b8ta4428858eetadb8a}

#NoSQL Database Settings
spring.data.mongodb.host=${NoSQL_HOST:localhost}
spring.data.mongodb.port=${NoSQL_PORT:27017}
spring.data.mongodb.database=${NoSQL_DB:SalusDB}
spring.data.mongodb.username=${NoSQL_USER:salus}
spring.data.mongodb.password=${NoSQL_PWD:Ba705b8ta4428858eetadb8a}
spring.data.mongodb.authentication-database=admin

#JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Flyway
spring.flyway.baseline-on-migrate=true
spring.flyway.enabled=true

#API Settings
spring.data.web.sort.sort-parameter=orderBy
server.port=7777
app.use-swagger=false

#Token Variables
api.security.token.secret=${JWT_SECRET:qwertyuiop}

#Brevo Settings
api.brevo.url=${BREVO_URL:https://api.brevo.com}
api.brevo.key=${BREVO_KEY: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}
api.brevo.reset-templete=${BREVO_RESET:2}

#RabbitMQ
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:salus}
spring.rabbitmq.password=${RABBIT_PWD:Ba705b8ta4428858eetadb8a}

#redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
