services:
  salus-api:
    image: salus-api
    container_name: salus-api
    build:
      context: Salus.API
    ports:
      - 7777:7777   
    environment:
      - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;
      - SQL_USER=sa
      - SQL_PWD=Ba705b8ta4428858eetadb8a

      - NoSQL_HOST=db-mongo
      - NoSQL_PORT=27017
      - NoSQL_DB=SalusDB
      - NoSQL_USER=salus
      - NoSQL_PWD=Ba705b8ta4428858eetadb8a

      - BREVO_URL="https://api.brevo.com"
      - BREVO_KEY="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"
      - BREVO_RESET=2

      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=salus
      - RABBIT_PWD=Ba705b8ta4428858eetadb8a

      - REDIS_HOST=db-redis
      - REDIS_PORT=6379
    networks:
      - salus-network

  # salus-communicator:
  #   image: salus-api
  #   container_name: alus-communicator
  #   build:
  #     context: Salus.Communicator
  #   ports:
  #     - 8081:7778   
  #   environment:
  #     - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;

  # salus-notificator:
  #   image: salus-api
  #   container_name: salus-notificator
  #   build:
  #     context: Salus.API
  #   ports:
  #     - 8082:7779   
  #   environment:
  #     - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;

  # salus-report:
  #   image: salus-api
  #   container_name: salus-report
  #   build:
  #     context: Salus.API
  #   ports:
  #     - 8083:7771   
  #   environment:
  #     - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;

volumes:
  mssql-data:

networks:
  salus-network:
    driver: bridge