services:
  salus-api:
    image: salus-api
    container_name: salus-api
    build:
      context: Salus.API
    ports:
      - 8080:7777   
    environment:
      - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;
  
  # salus-communicator:
  #   image: salus-api
  #   container_name: alus-communicator
  #   build:
  #     context: Salus.Communicator
  #   ports:
  #     - 8081:7778   
  #   environment:
  #     - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;

  # salus-notificator:
  #   image: salus-api
  #   container_name: salus-notificator
  #   build:
  #     context: Salus.API
  #   ports:
  #     - 8082:7779   
  #   environment:
  #     - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;

  # salus-report:
  #   image: salus-api
  #   container_name: salus-report
  #   build:
  #     context: Salus.API
  #   ports:
  #     - 8083:7771   
  #   environment:
  #     - SQL_CONN=jdbc:sqlserver://db-mssql;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;

volumes:
  mssql-data:

networks:
  salus-network:
    driver: bridge