services:
  db-mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-mssql
    environment:
      SA_PASSWORD: "Ba705b8ta4428858eetadb8a"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - salus-network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "salus"
      RABBITMQ_DEFAULT_PASS: "Ba705b8ta4428858eetadb8a"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  db-mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: "salus"
      MONGO_INITDB_ROOT_PASSWORD: "Ba705b8ta4428858eetadb8a" 
    volumes:
      - mongo_data:/data/db 

volumes:
  mssql-data:
  rabbitmq_data:
  mongo_data:

networks:
  salus-network:
    driver: bridge