# Stage 1: Build the application with Maven
FROM maven:3.8.6-eclipse-temurin-17 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the pom.xml file and download dependencies
COPY ["Sources/Salus.API/pom.xml", "/app/"]
RUN mvn dependency:go-offline

# Copy the entire project to the container
COPY ["Sources/Salus.API/", "/app/"]

# Compile and package the Spring Boot application (skipping tests to speed up build)
RUN mvn clean package -DskipTests

# Stage 2: Run the application
FROM openjdk:17-jdk-slim

# Set the working directory for the final container
WORKDIR /app

# Copy the JAR file from the Maven build stage
COPY --from=build /app/target/salus.api-0.0.1-SNAPSHOT.jar /app/salus.api-0.0.1-SNAPSHOT.jar

# Expose the port your Spring Boot app will run on
EXPOSE 8080

# Run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/app/salus.api-0.0.1-SNAPSHOT.jar"]
