spring.application.name=communicator
project.info.version=1.3

#MQTT Options
comm.mqtt.broker=${MQTT_BROKER:tcp://localhost:1883}

#NoSQL Database Settings
spring.data.mongodb.host=${NoSQL_HOST:localhost}
spring.data.mongodb.port=${NoSQL_PORT:27017}
spring.data.mongodb.database=${NoSQL_DB:SalusDB}
spring.data.mongodb.username=${NoSQL_USER:salus}
spring.data.mongodb.password=${NoSQL_PWD:Ba705b8ta4428858eetadb8a}
spring.data.mongodb.authentication-database=admin

#API Settings
server.port=7778