spring.application.name=notificator

#SQL Database Settings
spring.datasource.url=${SQL_CONN:jdbc:sqlserver://localhost;databaseName=SalusDB;encrypt=true;trustServerCertificate=true;applicationName=Notificator}
spring.datasource.username=${SQL_USER:sa}
spring.datasource.password=${SQL_PWD:Ba705b8ta4428858eetadb8a}

#NoSQL Database Settings
spring.data.mongodb.host=${NoSQL_HOST:localhost}
spring.data.mongodb.port=${NoSQL_PORT:27017}
spring.data.mongodb.database=${NoSQL_DB:SalusDB}
spring.data.mongodb.username=${NoSQL_USER:salus}
spring.data.mongodb.password=${NoSQL_PWD:Ba705b8ta4428858eetadb8a}
spring.data.mongodb.authentication-database=admin

#JPA
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#API Settings
server.port=7779

#RabbitMQ
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:salus}
spring.rabbitmq.password=${RABBIT_PWD:Ba705b8ta4428858eetadb8a}

#redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}