CREATE TABLE rabbitmq_queue
(
    Queue VARCHAR(50) NOT NULL,
    Exchange VARCHAR(50) NOT NULL,
    Routing_Key UNIQUEIDENTIFIER DEFAULT NEWSEQUENTIALID() PRIMARY KEY,
    Delayed BIT NOT NULL DEFAULT 0
);